remote_theme: PfeifferChPT/pc-cdn-template
name: "PC-CDN.DE - CDN (DE)"
title: "PC-CDN"
subtitle: ".de"
description: "Dies ist ein Content-Server des P.C. Netzwerk | PC-CDN.DE" #metadescription
mamarkdown: kramdown
highlighter: rouge # pygments or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:year/:month/:day/:title:output_ext
excerpt_separator: <!--more-->
templateserverurl: https://template.pc-cdn.de
themecolor: blue
themelogo: https://template.pc-cdn.de/assets/img/logo/logo.png
dummyimage: overlay-pattern.png
themeURI: none
themeBGimage: none
GallerieDir: none
hbbhomeurl: none
livereload: true
author: Christian Pfeiffer
since: 2017
# Pagination Settings 
#pagination:
#  enabled: true
#  per_page: 2
#  permalink: '/page/:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true
